
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"   # Monitoring HTTP
    command: ["-c", "/etc/nats/nats-server.conf"]
    volumes:
      # Montiamo la cartella dei certificati
      - ./certs:/etc/nats/certs:ro
      # Montiamo il file di configurazione
      - ./nats-server.conf:/etc/nats/nats-server.conf:ro

    # CLI interattivo, con shell e NATS CLI
  cli:
    image: natsio/nats-box:latest
    command: ["/bin/ash"]      # ash esiste in nats-box
    environment:
      - NATS_URL=nats://nats:4222  # user can run: docker-compose run cli nats sub ... / nats pub ...
    stdin_open: true
    tty: true
    depends_on:
      - nats

    

  server_a:
    build: ./server_a
    environment:
      - NATS_URL=nats://nats:4222
      - TLS_CERT_DIR=/etc/worker/certs
    volumes:
      - ./certs:/etc/worker/certs:ro
    depends_on:
      - nats

  server_b:
    build: ./server_b
    environment:
      - NATS_URL=nats://nats:4222
      - TLS_CERT_DIR=/etc/worker/certs
    volumes:
      - ./certs:/etc/worker/certs:ro
    depends_on:
      - nats
