[package]
name = "publisher"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.41"
tokio = { version = "1", features = ["full"] }
serde_json   = "1.0"
chrono       = { version = "0.4", features = ["serde"] }